class Constants:
    INTERNAL_SERVER_ERROR = 'Internal server error'
    LOGIN_SUCCESSFULL = 'Login successfully'
    LOGOUT = 'Logout successfully'
    UPDATE = 'Updated successfully'
    CREATE = 'Created successfully'
    CREATE_UNSUCCESFFULL = 'Create'
    UPDATE_UNSUCCESSFULL = 'Update unsuccessfull'
    PHONE_MISSING = 'PHONE_NUMBER_MISSING'
    PAYLOAD_MISSING = 'PAYLOAD_MISSING'
    REGISTRATION_UNSUCCESSFULL = 'REGISTRATION_UNSUCCESSFULL'
    USER_MAPPING_NOT_CREATED = 'USER_MAPPING_NOT_CREATED'
    USER_STATUS_NOT_CREATED = 'USER_STATUS_NOT_CREATED'
    SESSION_NOT_UPDATED = ''
    SESSION_NOT_CREATED = 'SESSION_NOT_CREATED'
    SESSION_CREATED = 'SESSION_CREATED'
    USER_NOT_FOUND = 'User not found'
    USER_DETAILS = 'USER_DETAILS'
    USER_NOT_UPDATED = 'USER_NOT_UPDATED'
    DETAILS = 'DETAILS'
    REFRESH_TOKEN_MISSING = 'REFRESH_TOKEN_MISSING'
    DEVICE_ID_MISSING= 'Device id is missing'
    SESSION_NOT_FOUND = 'Session not found'
    NOT_SYNC = 'Contacts not synced'
    SYNC = 'Contacts synced'
    PARAMS_MISSING = 'PARAMS_MISSING'
    CANT_BLOCK_YOURSELF = 'CANNOT_BLOCK_YOURSELF'
    INVITE_USER = 'Need to send inivitation'
    BLOCKED = 'User is blocked Successfully'
    UNBLOCKED = 'User is unblocked Successfully'
    NOT_ABLE_TO_BLOCK = 'Unable to block'
    WRONG_LENGTH_OF_LIST_OF_MEMBERS = 'Wrong lenght of list members'
    INDIVIDUAL_ROOM_NOT_CREATED = 'Individual room not created'
    ROOM_CREATE_UNSUCCESSFULL = 'ROOM_CREATE_UNSUCCESSFULL'
    GROUP_MEMBERS_ADDED_SUCCESSFULLY = 'GROUP_MEMBERS_ADDED_SUCCESSFULLY'
    GROUP_MEMBERS_ADDITION_UNSUCCESSFULL = 'Group members addition unsuccessfull'
    ROOM_CREATE = 'ROOM_CREATED_SUCCESSFULL'
    CANT_MAKE_YOURSELF_ADMIN = 'CANT_MAKE_YOURSELF_ADMIN'
    YOU_ARE_NOT_ADMIN = 'You are not admin'
    YOU_ARE_NOT_PRESENT_IN_THE_GROUP = 'You are not present in the group'
    MEMBER_NOT_FOUND = 'Member not found'
    ALREADY_ADMIN = 'Already admin'
    UPDATED_AS_ADMIN = 'Updated as admin'
    CANT_REMOVE_ANOTHER_ADMIN = 'You cant remove another admin'
    MEMBER_REMOVED_SUCCESSFULLY= 'Member removed successfully'
    LEFT_SUCCESSFULLY = 'Left successfully'
    CANT_REMOVE_YOURSELF = 'CANT_REMOVE_YOURSELF'
    SUCCESSFULL = 'Successfull'
    UNSUCCESSFULL='Unsuccessfull'
    WRONG_OTP = 'Wrong otp'
    OTP_VERIFIED = 'Otp verified'
    CANT_ADMIN_RIGHTS = 'Giving admin rights '
    OTP_SENT_SUCCESSFULLY = 'Otp sent successfully'
    CANT_CREATE_REFRESH_TOKEN = 'Token has not been created'
    UNABLE_TO_MAKE_ADMIN = 'Unable to make admin'
    CANT_FETECH_DETAILS = 'Cannot fetch details'
    UNABLE_TO_LEAVE_GROUP = 'Unable to leave group'
    UNABLE_TO_REMOVE_MEMBER = 'Unable to remove member'
    OTP_NOT_SENT = 'Unable to send otp'
    OTP_NOT_VERIFIED = 'Unable to verify otp'
    


class ErrMsgCode():
    # 400
    VALIDATION_ERROR = 'VALIDATION_ERROR'
    #500
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'
    #404
    USER_NOT_FOUND = 'USER_NOT_FOUND'
    WRONG_OTP = 'WRONG_OTP'
    PAYLOAD_INCORRECT = 'PAYLOAD_INCORRECT'
    FORBIDDEN = 'FORBIDDEN_ACTION'
    PAYLOAD_MISSING = 'PAYLOAD_MISSING'
    SESSION_NOT_FOUND = 'SESSION_NOT_FOUND'
    BLACKLISTED_TOKEN = 'BLACKLISTED_TOKEN'
    MEMBER_NOT_FOUND = 'MEMBER_NOT_FOUND'

class ErrMsg():
    USER_NOT_FOUND = "User not found"
    INTERNAL_SERVER_ERROR = "Internal server error"
    WRONG_OTP = "Wrong otp"
    WRONG_LENGTH_OF_LIST_OF_MEMBERS = 'Wrong lenght of list members'
    ROOM_TYPE_WRONG = "Room type wrong"
    # PAYLOAD_INCORRECT= ''
    ROOM_ID_MEMBER_ID_MISSING = 'Room_id/Member_id is missing'
    ROOM_ID_IS_MISSING = 'Room id is missing'
    CANT_MAKE_YOURSELF_ADMIN = 'Cant make yourself admin'
    WRONG_OTP = 'Given otp is wrong'
    REFRESH_TOKEN_MISSING = 'Refresh token is missing'
    DEVICE_ID_MISSING = 'Device id is missing'
    SESSION_NOT_FOUND = 'Session not found for given device'
    CONTACT_NAME_OR_NUMBER_MISSING = 'Contact name/contact number missing'
    TO_CHAT_USER_ID_MISSING = 'Provide the user to block'
    NOT_ABLE_TO_BLOCK_YOURSELF = 'Not able to block yourself'
    YOU_ARE_NOT_PRESENT_IN_THE_GROUP = 'You are not present in the group'
    YOU_ARE_NOT_ADMIN = 'You are not admin'
    MEMBER_NOT_FOUND = 'Member is missing'
    CANT_REMOVE_YOURSELF = 'You cant remove yourself'
    CANT_REMOVE_ANOTHER_ADMIN = 'Cant remove another admin'


