# Generated by Django 4.2.6 on 2023-10-22 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='last_msg_sender_id',
            field=models.ForeignKey(blank=True, db_column='last_msg_sender_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='last_msg_type',
            field=models.CharField(choices=[('text', 'text'), ('image', 'image'), ('video', 'video'), ('location', 'location'), ('contact', 'contact'), ('document', 'document')], default='text', max_length=50),
        ),
    ]
