# Generated by Django 4.2.6 on 2023-11-24 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_messagehistory_read_by_chat_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagehistory',
            name='delivered_to_chat_user_id',
            field=models.ForeignKey(blank=True, db_column='delivered_to_chat_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivered_to', to='users.usersmapping'),
        ),
    ]
