# Generated by Django 4.2.6 on 2023-10-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_room_last_msg_alter_room_last_msg_sent_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='last_msg_type',
            field=models.CharField(blank=True, choices=[('text', 'text'), ('image', 'image'), ('video', 'video'), ('location', 'location'), ('contact', 'contact'), ('document', 'document'), ('None', None)], max_length=50, null=True),
        ),
    ]
