# Generated by Django 4.2.6 on 2023-11-27 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_messagehistory_delivered_to_chat_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='chat_user_id',
            field=models.ForeignKey(db_column='chat_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='session_chat_user_id', to='users.usersmapping'),
        ),
    ]
