# Generated by Django 4.2.6 on 2023-10-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_groupmembers_removed_by_alter_groupmembers_member_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmembers',
            old_name='group_picture',
            new_name='profile_picture',
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
