# Generated by Django 4.2.6 on 2023-10-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_group_picture_groupmembers_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_archived',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off')], default='off', max_length=150),
        ),
    ]
